# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('news_title', models.CharField(max_length=200, null=True)),
                ('news_url', models.CharField(max_length=500, null=True)),
                ('upvotes', models.CharField(max_length=10, null=True)),
                ('downvotes', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
