# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
